title: Mykola Semenov
url: https://mykola-semenov.github.io
baseurl: ""
description: >
    Machine Learning, Computational Methods, and Software Development

permalink: /:slug

goat_counter: "mykola-semenov"

date_format: "%Y-%m-%d"

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
